domain_path: /home/eden/Documents/ps-pl-nand-gate-software/platform/export/platform/sw/standalone_ps7_cortexa9_0
app_src_dir: /tools/Xilinx/2025.1/Vitis/data/embeddedsw/lib/sw_apps/hello_world
template: hello_world
lang: c
