domain_path: /home/eden/Documents/vivado-experiments/ps-pl-iic-control-software/platform-v2/export/platform-v2/sw/standalone_ps7_cortexa9_0
app_src_dir: /tools/Xilinx/2025.1/Vitis/data/embeddedsw/lib/sw_apps/empty_application
template: empty_application
lang: c
